"""
Starter content seeded into every new GoPhish instance on provision.
Called from server.py after the container is up and the API key is extracted.
"""

import json, ssl, urllib.request, urllib.error, time

TRAINING_URL = "https://edgeiqlabs.com/phishsim/"

def _gophish(admin_port, api_key, endpoint, payload):
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        f"https://localhost:{admin_port}/api/{endpoint}",
        data=data, method="POST",
        headers={"Content-Type": "application/json", "Authorization": api_key}
    )
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        return json.loads(e.read())
    except Exception as ex:
        return {"error": str(ex)}


def seed_instance(admin_port, api_key):
    """Post all starter templates, landing pages, and sample groups to a fresh GoPhish instance."""
    results = {"templates": [], "pages": [], "groups": [], "smtps": []}

    # ── EMAIL TEMPLATES ───────────────────────────────────────────────────────

    templates = [
      {
        "name": "IT Helpdesk — Password Expiring in 24 Hours",
        "subject": "ACTION REQUIRED: Your password expires in 24 hours",
        "text": "Hi {{.FirstName}},\n\nURGENT: Your network password expires in 24 hours.\n\nAccount: {{.Email}}\nSystems affected: Email, VPN, SharePoint, Teams\n\nUpdate your password now: {{.URL}}\n\nIT Help Desk",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:6px;overflow:hidden;border:1px solid #ddd;}.header{background:#1a1a2e;padding:18px 28px;}.header-title{color:#fff;font-size:16px;font-weight:700;}.body{padding:32px;color:#333;font-size:14px;line-height:1.7;}.urgent{background:#fef2f2;border-left:4px solid #ef4444;padding:14px 16px;margin:16px 0;border-radius:0 4px 4px 0;}.btn{display:inline-block;background:#ef4444;color:#fff;text-decoration:none;padding:12px 28px;border-radius:5px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #eee;}</style></head><body><div class="wrap"><div class="header"><span class="header-title">&#128274; IT Help Desk</span></div><div class="body"><p>Hi {{.FirstName}},</p><div class="urgent"><strong>&#9200; Urgent:</strong> Your network password expires in <strong>24 hours</strong>.</div><p>Account: {{.Email}}<br/>Systems: Email, VPN, SharePoint, Teams</p><a href="{{.URL}}" class="btn">Update Password Now</a></div><div class="footer">IT Help Desk &middot; Internal Systems</div></div></body></html>"""
      },
      {
        "name": "DocuSign — Document Awaiting Your Signature",
        "subject": "{{.FirstName}}, please sign: Confidential Agreement",
        "text": "Hi {{.FirstName}},\n\nYour signature is required on: Confidential_Agreement_2026.pdf\nExpires in 48 hours\n\nReview and sign: {{.URL}}\n\nDocuSign",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Helvetica Neue',Arial,sans-serif;background:#f7f7f7;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #e0e0e0;border-radius:4px;}.header{background:#fff;padding:20px 32px;border-bottom:3px solid #ffcc00;}.logo{font-size:22px;font-weight:800;color:#333;}.logo span{color:#ffcc00;}.body{padding:32px;font-size:14px;color:#333;line-height:1.6;}.doc-box{border:1px solid #ddd;border-radius:6px;padding:18px;margin:20px 0;}.doc-name{font-weight:700;font-size:15px;}.doc-meta{font-size:12px;color:#888;margin-top:3px;}.btn{display:inline-block;background:#ffcc00;color:#333;text-decoration:none;padding:12px 32px;border-radius:4px;font-weight:800;font-size:15px;margin:16px 0;}.footer{background:#f7f7f7;padding:16px 32px;font-size:11px;color:#aaa;border-top:1px solid #e0e0e0;}</style></head><body><div class="wrap"><div class="header"><div class="logo">Docu<span>Sign</span></div></div><div class="body"><p>Hi {{.FirstName}},</p><p><strong>Your signature is required:</strong></p><div class="doc-box"><div class="doc-name">Confidential_Agreement_2026.pdf</div><div class="doc-meta">Sent by: legal@company-docs.com &middot; Expires in 48 hours</div></div><a href="{{.URL}}" class="btn">Review &amp; Sign Document</a></div><div class="footer">DocuSign &middot; 221 Main Street &middot; San Francisco, CA 94105</div></div></body></html>"""
      },
      {
        "name": "FedEx — Package Delivery Attempt Failed",
        "subject": "FedEx: Delivery attempt failed — action required",
        "text": "Hi {{.FirstName}},\n\nDelivery attempt failed for tracking #774-8912-3847-001.\nYou have 3 business days to reschedule.\n\nSchedule redelivery: {{.URL}}\n\nFedEx Customer Service",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f2f2f2;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #ddd;}.header-inner{background:#ff6200;padding:14px 28px;}.logo{color:#fff;font-size:24px;font-weight:900;}.body{padding:28px;font-size:14px;color:#333;line-height:1.6;}.tracking-box{background:#f8f8f8;border:1px solid #ddd;padding:16px;margin:16px 0;border-radius:4px;}.tracking-num{font-family:monospace;font-size:16px;font-weight:700;color:#4d148c;}.status{background:#fff3cd;border:1px solid #ffc107;padding:12px 16px;border-radius:4px;margin:16px 0;}.btn{display:inline-block;background:#ff6200;color:#fff;text-decoration:none;padding:12px 28px;border-radius:3px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#4d148c;padding:14px 28px;font-size:11px;color:#ccc;}</style></head><body><div class="wrap"><div class="header-inner"><span class="logo">FedEx</span></div><div class="body"><p>Hi {{.FirstName}},</p><p>We attempted to deliver your package but were unable to complete delivery.</p><div class="tracking-box">Tracking: <span class="tracking-num">774-8912-3847-001</span></div><div class="status">&#9888;&#65039; <strong>Delivery Attempt Failed</strong> — Signature required.</div><p>You have <strong>3 business days</strong> to reschedule or the package will be returned.</p><a href="{{.URL}}" class="btn">Schedule Redelivery</a></div><div class="footer">FedEx &middot; 942 South Shady Grove Road &middot; Memphis, TN 38120</div></div></body></html>"""
      },
      {
        "name": "CEO — Urgent Wire Transfer Request",
        "subject": "Urgent — need this handled today",
        "text": "Hi {{.FirstName}},\n\nI'm in meetings today and need you to handle a wire transfer for a vendor. Time sensitive — needs to be done before EOD.\n\nReview vendor contract: {{.URL}}\n\nThanks,\nJames R. Mitchell\nCEO",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#fff;margin:0;padding:24px;}.body{max-width:560px;font-size:14px;color:#333;line-height:1.8;}.sig{margin-top:24px;font-size:13px;color:#555;border-top:1px solid #eee;padding-top:12px;}</style></head><body><div class="body"><p>Hi {{.FirstName}},</p><p>I'm in back-to-back meetings today and need you to handle a wire transfer for a vendor — time sensitive, needs to be done before EOD. Please treat this as confidential for now.</p><p><a href="{{.URL}}">Review the vendor contract here</a> before we proceed.</p><p>Thanks,</p><div class="sig"><strong>James R. Mitchell</strong><br/>Chief Executive Officer<br/>&#128241; Sent from mobile</div></div></body></html>"""
      },
      {
        "name": "HR — Payroll Direct Deposit Update Required",
        "subject": "Action Required: Verify your direct deposit information",
        "text": "Hi {{.FirstName}},\n\nAll employees must verify direct deposit information by this Friday as part of our annual payroll update.\n\nVerify now: {{.URL}}\n\nHR Payroll Services",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:6px;overflow:hidden;border:1px solid #ddd;}.header{background:#16a34a;padding:18px 28px;}.header-title{color:#fff;font-size:17px;font-weight:700;}.body{padding:32px;font-size:14px;color:#374151;line-height:1.7;}.notice{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;padding:14px 16px;margin:16px 0;font-size:13px;}.btn{display:inline-block;background:#16a34a;color:#fff;text-decoration:none;padding:12px 28px;border-radius:5px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;}</style></head><body><div class="wrap"><div class="header"><div class="header-title">&#128101; HR &mdash; Payroll Services</div></div><div class="body"><p>Hi {{.FirstName}},</p><p>All employees must verify their direct deposit banking information by <strong>this Friday</strong> as part of our annual payroll system update.</p><div class="notice">&#10003; Routine verification. Failure to confirm may delay your next paycheck.</div><a href="{{.URL}}" class="btn">Verify Banking Information</a></div><div class="footer">Human Resources &middot; Payroll Services</div></div></body></html>"""
      },
      {
        "name": "Microsoft 365 — Suspicious Sign-In Alert",
        "subject": "Unusual sign-in activity detected on your account",
        "text": "Hi {{.FirstName}},\n\nSuspicious sign-in detected on your Microsoft account.\nLocation: Lagos, Nigeria\nIP: 197.234.240.5\n\nReview activity: {{.URL}}\n\nMicrosoft Account Team",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Segoe UI',Arial,sans-serif;background:#f3f2f1;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #e0e0e0;border-radius:4px;overflow:hidden;}.header{background:#0078d4;padding:20px 32px;}.logo-text{color:#fff;font-size:20px;font-weight:600;}.body{padding:32px;color:#323130;font-size:14px;line-height:1.6;}.alert-box{background:#fff4ce;border:1px solid #f7d948;border-radius:4px;padding:14px 16px;margin:16px 0;font-size:13px;}.detail-row{display:flex;gap:12px;margin:6px 0;font-size:13px;}.detail-label{color:#605e5c;width:100px;flex-shrink:0;}.btn{display:inline-block;background:#0078d4;color:#fff;text-decoration:none;padding:10px 24px;border-radius:2px;font-size:14px;font-weight:600;margin:20px 0;}.footer{background:#f3f2f1;padding:16px 32px;font-size:11px;color:#a19f9d;border-top:1px solid #e0e0e0;}</style></head><body><div class="wrap"><div class="header"><span class="logo-text">Microsoft</span></div><div class="body"><h2 style="font-size:20px;font-weight:600;margin:0 0 16px;">Review recent activity</h2><p>Hi {{.FirstName}},</p><p>We noticed a sign-in to your Microsoft account from an unfamiliar location.</p><div class="alert-box">&#9888;&#65039; <strong>Suspicious sign-in blocked</strong></div><div class="detail-row"><span class="detail-label">Location:</span><span>Lagos, Nigeria</span></div><div class="detail-row"><span class="detail-label">IP address:</span><span>197.234.240.5</span></div><a href="{{.URL}}" class="btn">Review Activity</a></div><div class="footer">Microsoft Corporation &middot; One Microsoft Way &middot; Redmond, WA 98052</div></div></body></html>"""
      },
      {
        "name": "Google Drive — File Shared With You",
        "subject": "{{.FirstName}}, someone shared a file with you",
        "text": "Hi {{.FirstName}},\n\nSarah K. shared a file: Q2_2026_Financial_Report_CONFIDENTIAL.xlsx\n\nOpen file: {{.URL}}\n\nGoogle Drive",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f1f3f4;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.12);}.header{padding:20px 28px;border-bottom:1px solid #e8eaed;font-size:20px;font-weight:400;color:#5f6368;}.body{padding:32px;font-size:14px;color:#202124;line-height:1.6;}.file-card{border:1px solid #e8eaed;border-radius:8px;padding:16px 20px;margin:20px 0;}.file-name{font-weight:500;font-size:15px;color:#1a73e8;}.file-meta{font-size:12px;color:#5f6368;margin-top:4px;}.btn{display:inline-block;background:#1a73e8;color:#fff;text-decoration:none;padding:10px 24px;border-radius:4px;font-weight:500;font-size:14px;margin:16px 0;}.footer{padding:16px 28px;font-size:11px;color:#9aa0a6;border-top:1px solid #e8eaed;}</style></head><body><div class="wrap"><div class="header">Google Drive</div><div class="body"><p>Hi {{.FirstName}},</p><p><strong>Sarah K.</strong> has shared a file with you:</p><div class="file-card"><div class="file-name">Q2_2026_Financial_Report_CONFIDENTIAL.xlsx</div><div class="file-meta">Google Sheets &middot; Shared with edit access</div></div><a href="{{.URL}}" class="btn">Open in Google Sheets</a><p style="font-size:12px;color:#5f6368;">You need to sign in to view this document.</p></div><div class="footer">Google LLC &middot; 1600 Amphitheatre Parkway &middot; Mountain View, CA 94043</div></div></body></html>"""
      },
      {
        "name": "Zoom — Meeting Recording Available",
        "subject": "Recording available: All-hands meeting",
        "text": "Hi {{.FirstName}},\n\nThe recording for Company All-Hands Q2 Results is now available.\nDuration: 52 min | Passcode: 7291\n\nWatch: {{.URL}}\n\nZoom",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Helvetica,Arial,sans-serif;background:#f8f8f8;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e5e5e5;}.header{background:#2d8cff;padding:20px 28px;color:#fff;font-size:22px;font-weight:700;}.body{padding:32px;font-size:14px;color:#232333;line-height:1.6;}.meeting-card{background:#f8f9ff;border:1px solid #dde1ff;border-radius:8px;padding:18px 20px;margin:20px 0;}.meeting-title{font-weight:700;font-size:15px;margin-bottom:8px;}.meeting-meta{font-size:13px;color:#666;line-height:1.8;}.btn{display:inline-block;background:#2d8cff;color:#fff;text-decoration:none;padding:12px 24px;border-radius:6px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f8f8f8;padding:14px 28px;font-size:11px;color:#aaa;border-top:1px solid #e5e5e5;}</style></head><body><div class="wrap"><div class="header">zoom</div><div class="body"><p>Hi {{.FirstName}},</p><p>The recording for the following meeting is now available:</p><div class="meeting-card"><div class="meeting-title">Company All-Hands &mdash; Q2 Results &amp; Roadmap</div><div class="meeting-meta">Duration: 52 minutes<br/>Passcode: <strong>7291</strong></div></div><a href="{{.URL}}" class="btn">Watch Recording</a></div><div class="footer">Zoom Video Communications &middot; 55 Almaden Blvd &middot; San Jose, CA 95113</div></div></body></html>"""
      },
      {
        "name": "Apple ID — Account Access Suspended",
        "subject": "Your Apple ID has been locked — immediate action required",
        "text": "Hi {{.FirstName}},\n\nYour Apple ID ({{.Email}}) has been locked due to multiple failed sign-in attempts.\n\nUnlock your account: {{.URL}}\n\nApple Support",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:-apple-system,Helvetica,Arial,sans-serif;background:#f5f5f7;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.1);}.header{background:#000;padding:20px 28px;text-align:center;color:#fff;font-size:28px;}.body{padding:36px;font-size:15px;color:#1d1d1f;line-height:1.7;}.alert{background:#fff2f2;border:1px solid #ffcdd2;border-radius:8px;padding:16px;margin:20px 0;font-size:14px;}.btn{display:inline-block;background:#0071e3;color:#fff;text-decoration:none;padding:14px 32px;border-radius:8px;font-weight:600;font-size:16px;margin:20px 0;}.footer{background:#f5f5f7;padding:16px 28px;font-size:12px;color:#6e6e73;text-align:center;border-top:1px solid #e0e0e0;}</style></head><body><div class="wrap"><div class="header">&#63743;</div><div class="body"><h2 style="font-size:22px;font-weight:700;margin-bottom:12px;">Your Apple ID has been locked</h2><p>Hi {{.FirstName}},</p><p>We've detected multiple failed sign-in attempts on your Apple ID (<strong>{{.Email}}</strong>). To protect your account, we've temporarily locked it.</p><div class="alert">&#128274; <strong>Account locked</strong> &mdash; Unusual activity from an unrecognized device.</div><a href="{{.URL}}" class="btn">Unlock Apple ID</a></div><div class="footer">Apple Inc. &middot; One Apple Park Way &middot; Cupertino, CA 95014</div></div></body></html>"""
      },
      {
        "name": "LinkedIn — New Connection Request",
        "subject": "{{.FirstName}}, Sarah Chen wants to connect with you",
        "text": "Hi {{.FirstName}},\n\nSarah Chen (VP of Talent at Fortune 500) wants to connect on LinkedIn.\n\nView profile: {{.URL}}\n\nLinkedIn",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:-apple-system,Arial,sans-serif;background:#f3f2ef;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e0dfdc;}.header{background:#0a66c2;padding:14px 24px;color:#fff;font-size:20px;font-weight:900;}.body{padding:32px;font-size:14px;color:#191919;line-height:1.6;}.profile-card{display:flex;gap:16px;align-items:flex-start;border:1px solid #e0dfdc;border-radius:8px;padding:18px;margin:20px 0;}.avatar{width:56px;height:56px;border-radius:50%;background:#0a66c2;display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:20px;flex-shrink:0;}.name{font-weight:700;font-size:16px;}.title{font-size:13px;color:#666;margin-top:3px;}.mutual{font-size:12px;color:#0a66c2;margin-top:6px;}.btn-accept{display:inline-block;background:#0a66c2;color:#fff;text-decoration:none;padding:10px 24px;border-radius:24px;font-weight:600;font-size:14px;margin:4px;}.footer{background:#f3f2ef;padding:14px 24px;font-size:11px;color:#999;border-top:1px solid #e0dfdc;text-align:center;}</style></head><body><div class="wrap"><div class="header">in LinkedIn</div><div class="body"><p>Hi {{.FirstName}},</p><p><strong>Sarah Chen</strong> wants to connect:</p><div class="profile-card"><div class="avatar">S</div><div><div class="name">Sarah Chen</div><div class="title">VP of Talent Acquisition &middot; Fortune 500 Tech</div><div class="mutual">&#128101; 14 mutual connections</div></div></div><a href="{{.URL}}" class="btn-accept">Accept</a></div><div class="footer">LinkedIn Corporation &middot; Sunnyvale, CA 94085</div></div></body></html>"""
      },
      {
        "name": "Amazon — Suspicious Account Activity",
        "subject": "Action required: Suspicious activity on your Amazon account",
        "text": "Hi {{.FirstName}},\n\nA purchase of $847.00 was attempted from an unrecognized device in Bucharest, Romania.\n\nReview activity: {{.URL}}\n\nAmazon Security",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f0f2f2;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #ddd;}.header{background:#232f3e;padding:12px 24px;}.amz-logo{color:#ff9900;font-size:22px;font-weight:900;}.banner{background:#ff9900;padding:10px 24px;font-size:13px;font-weight:700;color:#111;text-align:center;}.body{padding:28px;font-size:14px;color:#111;line-height:1.7;}.alert{background:#fef8e7;border:1px solid #f0ad00;border-radius:4px;padding:14px;margin:16px 0;}.order-box{border:1px solid #ddd;border-radius:4px;padding:14px;margin:16px 0;font-size:13px;}.row{display:flex;justify-content:space-between;margin:4px 0;color:#555;}.btn{display:inline-block;background:#ff9900;color:#111;text-decoration:none;padding:10px 24px;border-radius:3px;font-weight:700;font-size:14px;margin:12px 0;}.footer{background:#232f3e;padding:14px 24px;font-size:11px;color:#999;text-align:center;}</style></head><body><div class="wrap"><div class="header"><span class="amz-logo">amazon</span></div><div class="banner">&#9888; Suspicious activity detected</div><div class="body"><p>Hi {{.FirstName}},</p><p>A purchase of <strong>$847.00</strong> was attempted from an unrecognized device.</p><div class="order-box"><div class="row"><span>Location:</span><span>Bucharest, Romania</span></div><div class="row"><span>IP:</span><span>188.26.157.44</span></div><div class="row"><span>Amount:</span><strong>$847.00</strong></div></div><a href="{{.URL}}" class="btn">Secure My Account</a></div><div class="footer">Amazon.com</div></div></body></html>"""
      },
      {
        "name": "PayPal — Unusual Activity, Account Limited",
        "subject": "Your account access has been limited",
        "text": "Hi {{.FirstName}},\n\nUnusual activity detected on your PayPal account. We've temporarily limited your access.\n\nRestore access: {{.URL}}\n\nPayPal",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Helvetica Neue',Arial,sans-serif;background:#f5f7fa;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:4px;overflow:hidden;border:1px solid #e0e7ef;}.header{background:#003087;padding:18px 28px;text-align:center;}.pp-logo{color:#fff;font-size:26px;font-weight:900;}.pp-logo span{color:#009cde;}.body{padding:32px;font-size:14px;color:#2c2e2f;line-height:1.7;}.notice{background:#fff3cd;border:1px solid #ffc107;border-radius:4px;padding:14px;margin:16px 0;font-size:13px;}.btn{display:inline-block;background:#009cde;color:#fff;text-decoration:none;padding:12px 32px;border-radius:25px;font-weight:700;font-size:15px;margin:16px 0;}.footer{background:#f5f7fa;padding:14px 28px;font-size:11px;color:#9da3aa;border-top:1px solid #e0e7ef;text-align:center;}</style></head><body><div class="wrap"><div class="header"><div class="pp-logo">Pay<span>Pal</span></div></div><div class="body"><h2 style="font-size:20px;font-weight:700;margin-bottom:12px;">We've limited your account</h2><p>Hi {{.FirstName}},</p><p>We've noticed unusual activity and temporarily limited your ability to send money and make payments.</p><div class="notice">&#9888; <strong>Action required:</strong> Verify your identity to restore full access.</div><a href="{{.URL}}" class="btn">Restore Account Access</a></div><div class="footer">PayPal &middot; 2211 North First Street &middot; San Jose, CA 95131</div></div></body></html>"""
      },
      {
        "name": "IT Security — MFA Enrollment Required by Friday",
        "subject": "REQUIRED: Enroll in multi-factor authentication by Friday",
        "text": "Hi {{.FirstName}},\n\nAll employees must enroll in MFA by this Friday or lose access to corporate systems.\n\nEnroll now: {{.URL}}\n\nIT Security Team",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:6px;overflow:hidden;border:1px solid #ddd;}.header{background:#1a1a2e;padding:18px 28px;display:flex;align-items:center;gap:12px;}.header-title{color:#fff;font-size:17px;font-weight:700;}.header-badge{background:#ef4444;color:#fff;font-size:10px;font-weight:700;padding:3px 8px;border-radius:10px;text-transform:uppercase;}.body{padding:32px;font-size:14px;color:#333;line-height:1.7;}.deadline-box{background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:16px;margin:16px 0;text-align:center;}.deadline-label{font-size:12px;text-transform:uppercase;color:#ef4444;font-weight:700;letter-spacing:.08em;}.deadline-date{font-size:24px;font-weight:900;color:#dc2626;margin-top:4px;}.btn{display:inline-block;background:#1a1a2e;color:#fff;text-decoration:none;padding:12px 28px;border-radius:5px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #eee;}</style></head><body><div class="wrap"><div class="header"><span class="header-title">&#128274; IT Security</span><span class="header-badge">Action Required</span></div><div class="body"><p>Hi {{.FirstName}},</p><p>All employees must enroll in <strong>Multi-Factor Authentication (MFA)</strong> by the deadline. Accounts not enrolled will lose access to email, VPN, and all corporate applications.</p><div class="deadline-box"><div class="deadline-label">Enrollment Deadline</div><div class="deadline-date">This Friday &mdash; EOD</div></div><a href="{{.URL}}" class="btn">Enroll in MFA Now</a></div><div class="footer">IT Security Team &middot; Internal Communication</div></div></body></html>"""
      },
      {
        "name": "IT Security — New Device Signed Into Your Account",
        "subject": "New sign-in on an unrecognized device",
        "text": "Hi {{.FirstName}},\n\nA new device signed into your corporate account from Amsterdam, Netherlands.\n\nIf this wasn't you, secure your account immediately.\n\nReview sign-in: {{.URL}}\n\nIT Security",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:6px;overflow:hidden;border:1px solid #ddd;}.header{background:#1a1a2e;padding:18px 28px;}.header-title{color:#fff;font-size:17px;font-weight:700;}.alert-strip{background:#ef4444;padding:10px 28px;color:#fff;font-size:13px;font-weight:700;text-align:center;}.body{padding:32px;font-size:14px;color:#333;line-height:1.7;}.device-card{background:#fef2f2;border:1px solid #fecaca;border-radius:6px;padding:16px;margin:16px 0;}.device-row{display:flex;gap:10px;margin:5px 0;font-size:13px;}.device-label{color:#666;width:90px;flex-shrink:0;}.device-val{font-weight:600;color:#111;}.btn-secure{display:inline-block;background:#ef4444;color:#fff;text-decoration:none;padding:12px 28px;border-radius:5px;font-weight:700;font-size:14px;margin:8px 8px 8px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #eee;}</style></head><body><div class="wrap"><div class="header"><span class="header-title">&#128274; IT Security Alert</span></div><div class="alert-strip">&#9888; New sign-in on an unrecognized device</div><div class="body"><p>Hi {{.FirstName}},</p><div class="device-card"><div class="device-row"><span class="device-label">Device:</span><span class="device-val">MacBook Pro (unknown)</span></div><div class="device-row"><span class="device-label">Location:</span><span class="device-val">Amsterdam, Netherlands</span></div><div class="device-row"><span class="device-label">IP:</span><span class="device-val">82.217.93.14</span></div></div><p><strong>If this wasn't you</strong>, your credentials may be compromised.</p><a href="{{.URL}}" class="btn-secure">Secure My Account</a></div><div class="footer">IT Security Team &middot; Automated alert</div></div></body></html>"""
      },
      {
        "name": "SharePoint — Confidential Document Shared",
        "subject": "{{.FirstName}}, a confidential document was shared with you",
        "text": "Hi {{.FirstName}},\n\nJennifer Walsh (CTO) shared a confidential document on SharePoint.\n\nDocument: Q3_Board_Presentation_DRAFT.pptx\n\nView document: {{.URL}}\n\nMicrosoft SharePoint",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Segoe UI',Arial,sans-serif;background:#f3f2f1;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #e0e0e0;border-radius:4px;overflow:hidden;}.header{background:#0078d4;padding:18px 28px;}.header-text{color:#fff;font-size:18px;font-weight:700;}.body{padding:32px;font-size:14px;color:#323130;line-height:1.6;}.doc-card{border:1px solid #edebe9;border-radius:4px;padding:16px 18px;margin:20px 0;display:flex;gap:14px;align-items:center;}.doc-icon{font-size:36px;flex-shrink:0;}.doc-name{font-weight:700;font-size:15px;color:#0078d4;}.doc-meta{font-size:12px;color:#605e5c;margin-top:4px;}.confidential-badge{display:inline-block;background:#fde7e9;color:#a4262c;font-size:10px;font-weight:700;padding:2px 8px;border-radius:2px;text-transform:uppercase;margin-top:6px;}.btn{display:inline-block;background:#0078d4;color:#fff;text-decoration:none;padding:10px 24px;border-radius:2px;font-weight:600;font-size:14px;margin:12px 0;}.footer{background:#f3f2f1;padding:14px 28px;font-size:11px;color:#a19f9d;border-top:1px solid #e0e0e0;}</style></head><body><div class="wrap"><div class="header"><span class="header-text">&#128196; SharePoint</span></div><div class="body"><p>Hi {{.FirstName}},</p><p><strong>Jennifer Walsh</strong> has shared a document with you:</p><div class="doc-card"><div class="doc-icon">&#128202;</div><div><div class="doc-name">Q3_Board_Presentation_DRAFT.pptx</div><div class="doc-meta">Shared by jennifer.walsh@company.com</div><span class="confidential-badge">&#128274; Confidential</span></div></div><a href="{{.URL}}" class="btn">Open Document</a></div><div class="footer">Microsoft SharePoint</div></div></body></html>"""
      },
      {
        "name": "IT — VPN Certificate Expiring, Re-authenticate",
        "subject": "Your VPN certificate expires in 24 hours — action required",
        "text": "Hi {{.FirstName}},\n\nYour corporate VPN certificate expires in 24 hours. Re-authenticate to avoid losing remote access.\n\nRe-authenticate: {{.URL}}\n\nIT Infrastructure Team",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f0f2f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #dde1e7;}.header{background:#0f2347;padding:18px 28px;}.header-title{color:#fff;font-size:17px;font-weight:700;}.status-bar{background:#ff6b00;padding:10px 28px;font-size:13px;font-weight:700;color:#fff;}.body{padding:32px;font-size:14px;color:#1a1a2e;line-height:1.7;}.cert-box{background:#f8f9ff;border:1px solid #dde1ff;border-radius:6px;padding:16px;margin:16px 0;font-size:13px;}.cert-row{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #eef0f8;}.cert-row:last-child{border:none;}.expires{color:#dc2626;}.btn{display:inline-block;background:#0f2347;color:#fff;text-decoration:none;padding:12px 28px;border-radius:6px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f0f2f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #dde1e7;}</style></head><body><div class="wrap"><div class="header"><div class="header-title">&#128274; IT Infrastructure &mdash; VPN</div></div><div class="status-bar">&#9888; Certificate expiring in less than 24 hours</div><div class="body"><p>Hi {{.FirstName}},</p><p>Your corporate VPN certificate is about to expire. After expiration you will <strong>lose remote access</strong> to all internal systems.</p><div class="cert-box"><div class="cert-row"><span>Status:</span><span class="expires">Expiring Soon</span></div><div class="cert-row"><span>Access:</span><span>VPN &middot; Remote Desktop &middot; Internal Apps</span></div></div><a href="{{.URL}}" class="btn">Renew VPN Certificate</a></div><div class="footer">IT Infrastructure Team</div></div></body></html>"""
      },
      {
        "name": "HR — Benefits Open Enrollment Closes Friday",
        "subject": "Last chance: Benefits enrollment closes this Friday",
        "text": "Hi {{.FirstName}},\n\nLast reminder to complete your 2026 benefits enrollment. Missing the deadline means you'll keep last year's plan with no changes.\n\nEnroll now: {{.URL}}\n\nHR Benefits Team",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:6px;overflow:hidden;border:1px solid #ddd;}.header{background:#1e6b4a;padding:18px 28px;}.header-title{color:#fff;font-size:17px;font-weight:700;}.countdown{background:#e8f5ee;border-bottom:2px solid #1e6b4a;padding:14px 28px;text-align:center;}.countdown-label{font-size:12px;font-weight:700;text-transform:uppercase;color:#1e6b4a;letter-spacing:.06em;}.countdown-val{font-size:28px;font-weight:900;color:#1e6b4a;margin-top:4px;}.body{padding:32px;font-size:14px;color:#333;line-height:1.7;}.btn{display:inline-block;background:#1e6b4a;color:#fff;text-decoration:none;padding:12px 28px;border-radius:5px;font-weight:700;font-size:14px;margin:16px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #eee;}</style></head><body><div class="wrap"><div class="header"><div class="header-title">&#128104;&#8205;&#128187; HR Benefits &mdash; Open Enrollment 2026</div></div><div class="countdown"><div class="countdown-label">Enrollment closes in</div><div class="countdown-val">2 Days</div></div><div class="body"><p>Hi {{.FirstName}},</p><p>This is your final reminder to complete your <strong>2026 Benefits Enrollment</strong>. If you miss the Friday deadline, you'll be auto-enrolled in last year's plan with no changes permitted until next year.</p><a href="{{.URL}}" class="btn">Complete Enrollment Now</a></div><div class="footer">Human Resources &middot; Benefits Administration</div></div></body></html>"""
      },
      {
        "name": "Adobe Sign — NDA Awaiting Your Signature",
        "subject": "Please sign: Non-Disclosure Agreement",
        "text": "Hi {{.FirstName}},\n\nYou have a document requiring your signature in Adobe Sign. NDA expires in 48 hours.\n\nSign document: {{.URL}}\n\nAdobe Sign",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:4px;overflow:hidden;border:1px solid #ddd;}.header{background:#fa0f00;padding:16px 28px;display:flex;align-items:center;gap:12px;}.adobe-logo{color:#fff;font-size:22px;font-weight:900;}.header-product{color:#fff;font-size:16px;font-weight:400;opacity:.9;}.body{padding:32px;font-size:14px;color:#2c2c2c;line-height:1.7;}.doc-banner{background:#fff8f8;border:1px solid #ffcccc;border-radius:4px;padding:16px 18px;margin:20px 0;display:flex;gap:14px;align-items:flex-start;}.doc-icon{font-size:36px;flex-shrink:0;}.doc-name{font-weight:700;font-size:15px;}.doc-meta{font-size:12px;color:#888;margin-top:4px;line-height:1.8;}.expires-badge{display:inline-block;background:#fde7e9;color:#a4262c;font-size:11px;font-weight:700;padding:2px 8px;border-radius:10px;}.btn{display:inline-block;background:#fa0f00;color:#fff;text-decoration:none;padding:12px 28px;border-radius:4px;font-weight:700;font-size:14px;margin:12px 0;}.footer{background:#f5f5f5;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #e5e5e5;text-align:center;}</style></head><body><div class="wrap"><div class="header"><span class="adobe-logo">Adobe</span><span class="header-product">Acrobat Sign</span></div><div class="body"><p>Hi {{.FirstName}},</p><p><strong>Robert Chang (Legal)</strong> has sent you a document for signature:</p><div class="doc-banner"><div class="doc-icon">&#128221;</div><div><div class="doc-name">Mutual Non-Disclosure Agreement 2026</div><div class="doc-meta">Sent by: robert.chang@company.com<br/><span class="expires-badge">Expires in 48 hours</span></div></div></div><a href="{{.URL}}" class="btn">Review and Sign</a></div><div class="footer">Adobe Inc. &middot; 345 Park Avenue &middot; San Jose, CA 95110</div></div></body></html>"""
      },
      {
        "name": "IT — OneDrive Storage 95% Full",
        "subject": "Your OneDrive storage is almost full",
        "text": "Hi {{.FirstName}},\n\nYour OneDrive storage is 95% full (47.5 GB of 50 GB used). Sign in to manage your files.\n\nManage storage: {{.URL}}\n\nMicrosoft OneDrive",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Segoe UI',Arial,sans-serif;background:#f3f2f1;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border:1px solid #e0e0e0;border-radius:4px;overflow:hidden;}.header{background:#0078d4;padding:18px 28px;}.header-text{color:#fff;font-size:18px;font-weight:700;}.body{padding:32px;font-size:14px;color:#323130;line-height:1.7;}.storage-widget{border:1px solid #edebe9;border-radius:6px;padding:20px;margin:20px 0;}.storage-label{display:flex;justify-content:space-between;font-size:13px;color:#605e5c;margin-bottom:8px;}.storage-bar-bg{background:#edebe9;border-radius:4px;height:10px;overflow:hidden;}.storage-bar-fill{background:#d83b01;height:10px;width:95%;border-radius:4px;}.storage-numbers{font-size:13px;color:#605e5c;margin-top:8px;text-align:right;}.btn{display:inline-block;background:#0078d4;color:#fff;text-decoration:none;padding:10px 24px;border-radius:2px;font-weight:600;font-size:14px;margin:12px 0;}.footer{background:#f3f2f1;padding:14px 28px;font-size:11px;color:#a19f9d;border-top:1px solid #e0e0e0;}</style></head><body><div class="wrap"><div class="header"><span class="header-text">&#9729;&#65039; Microsoft OneDrive</span></div><div class="body"><p>Hi {{.FirstName}},</p><p>Your OneDrive storage is almost full. When it fills, files stop syncing and backups halt.</p><div class="storage-widget"><div class="storage-label"><span>OneDrive</span><span>95% used</span></div><div class="storage-bar-bg"><div class="storage-bar-fill"></div></div><div class="storage-numbers"><strong style="color:#d83b01;">47.5 GB</strong> used of 50 GB</div></div><a href="{{.URL}}" class="btn">Manage Storage</a></div><div class="footer">Microsoft Corporation &middot; Redmond, WA 98052</div></div></body></html>"""
      },
      {
        "name": "Slack — You Have a Direct Message Waiting",
        "subject": "{{.FirstName}}, you have a DM from your manager",
        "text": "Hi {{.FirstName}},\n\nYou have an unread direct message from David Park (your manager) in Slack.\n\nView message: {{.URL}}\n\nSlack",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:Arial,sans-serif;background:#f8f8f8;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e8e8e8;}.header{background:#4a154b;padding:16px 28px;display:flex;align-items:center;gap:10px;}.slack-logo{color:#fff;font-size:22px;font-weight:900;}.badge{background:#e01e5a;color:#fff;font-size:11px;font-weight:700;padding:2px 7px;border-radius:10px;margin-left:8px;}.body{padding:32px;font-size:14px;color:#1d1c1d;line-height:1.6;}.msg-card{background:#f8f8f8;border-left:4px solid #4a154b;border-radius:0 8px 8px 0;padding:16px 18px;margin:20px 0;}.msg-sender{font-weight:700;color:#1d1c1d;margin-bottom:4px;}.msg-meta{font-size:12px;color:#888;margin-bottom:10px;}.msg-preview{font-size:14px;color:#555;font-style:italic;}.btn{display:inline-block;background:#4a154b;color:#fff;text-decoration:none;padding:11px 24px;border-radius:4px;font-weight:700;font-size:14px;margin-top:8px;}.footer{background:#f8f8f8;padding:14px 28px;font-size:11px;color:#999;border-top:1px solid #e8e8e8;text-align:center;}</style></head><body><div class="wrap"><div class="header"><span class="slack-logo">slack</span><span class="badge">1 new</span></div><div class="body"><p>Hi {{.FirstName}},</p><p>You have a new direct message:</p><div class="msg-card"><div class="msg-sender">David Park</div><div class="msg-meta">Manager &middot; Today at 2:14 PM</div><div class="msg-preview">"Hey, can you review this document before our 3pm call? It's time sensitive..."</div></div><a href="{{.URL}}" class="btn">Open in Slack</a></div><div class="footer">Slack Technologies &middot; San Francisco, CA 94105</div></div></body></html>"""
      },
      {
        "name": "Microsoft Teams — You've Been Added to a Channel",
        "subject": "You were added to the \"Executive Leadership\" team",
        "text": "Hi {{.FirstName}},\n\nYou've been added to the Executive Leadership team in Microsoft Teams.\n\nOpen Teams: {{.URL}}\n\nMicrosoft Teams",
        "html": """<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>body{font-family:'Segoe UI',Arial,sans-serif;background:#f3f2f1;margin:0;padding:0;}.wrap{max-width:600px;margin:32px auto;background:#fff;border-radius:4px;overflow:hidden;border:1px solid #e0e0e0;}.header{background:#6264a7;padding:18px 28px;display:flex;align-items:center;gap:12px;}.header-text{color:#fff;font-size:18px;font-weight:700;}.body{padding:32px;font-size:14px;color:#323130;line-height:1.7;}.team-card{border:1px solid #e0e0e0;border-radius:4px;padding:18px;margin:20px 0;display:flex;align-items:center;gap:14px;}.team-icon{width:48px;height:48px;background:#6264a7;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:22px;flex-shrink:0;}.team-name{font-weight:700;font-size:16px;}.team-meta{font-size:12px;color:#666;margin-top:4px;}.btn{display:inline-block;background:#6264a7;color:#fff;text-decoration:none;padding:10px 24px;border-radius:4px;font-weight:600;font-size:14px;margin:12px 0;}.footer{background:#f3f2f1;padding:14px 28px;font-size:11px;color:#a19f9d;border-top:1px solid #e0e0e0;text-align:center;}</style></head><body><div class="wrap"><div class="header"><span class="header-text">&#128101; Microsoft Teams</span></div><div class="body"><p>Hi {{.FirstName}},</p><p>You've been added to a new team:</p><div class="team-card"><div class="team-icon">&#127959;</div><div><div class="team-name">Executive Leadership</div><div class="team-meta">Added by: Jennifer Walsh (CTO) &middot; 12 members</div></div></div><a href="{{.URL}}" class="btn">Open Microsoft Teams</a></div><div class="footer">Microsoft Corporation &middot; Redmond, WA 98052</div></div></body></html>"""
      },
    ]

    # ── LANDING PAGES ─────────────────────────────────────────────────────────

    pages = [
      {
        "name": "Microsoft 365 — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Sign in to your account</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:"Segoe UI",Helvetica,Arial,sans-serif;background:#f2f2f2;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;padding:44px;width:100%;max-width:440px;border-radius:2px;box-shadow:0 2px 6px rgba(0,0,0,.15);}.ms-logo{font-size:21px;font-weight:600;color:#5e5e5e;margin-bottom:24px;}.ms-r{color:#f35325;}.ms-g{color:#81bc06;}.ms-b{color:#05a6f0;}.ms-y{color:#ffba08;}h1{font-size:24px;font-weight:600;color:#1b1b1b;margin-bottom:16px;}label{display:block;font-size:13px;margin-bottom:5px;}input{width:100%;border:1px solid #8a8886;border-radius:2px;padding:7px 10px;font-size:15px;outline:none;margin-bottom:12px;}.btn{width:100%;background:#0078d4;color:#fff;border:none;padding:10px;font-size:15px;font-weight:600;border-radius:2px;cursor:pointer;}</style></head><body><div class="card"><div class="ms-logo"><span class="ms-r">&#9632;</span><span class="ms-g">&#9632;</span><span class="ms-b">&#9632;</span><span class="ms-y">&#9632;</span> Microsoft</div><h1>Sign in</h1><form method="POST" action=""><label>Email, phone, or Skype</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign in</button></form></div></body></html>"""
      },
      {
        "name": "Google — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Sign in - Google Accounts</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:"Google Sans",Roboto,Arial,sans-serif;background:#f8f9fa;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;padding:48px 40px;width:100%;max-width:450px;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,.12);}.g-logo{font-size:22px;text-align:center;margin-bottom:8px;}.g-blue{color:#4285f4;}h1{font-size:24px;font-weight:400;text-align:center;margin-bottom:8px;}p.sub{font-size:16px;text-align:center;margin-bottom:28px;}label{display:block;font-size:12px;color:#444746;margin-bottom:6px;}input{width:100%;border:1px solid #dadce0;border-radius:4px;padding:12px 14px;font-size:16px;outline:none;margin-bottom:8px;}.btn{float:right;background:#1a73e8;color:#fff;border:none;padding:10px 24px;font-size:14px;font-weight:600;border-radius:4px;cursor:pointer;}.row{display:flex;justify-content:space-between;align-items:center;margin-top:8px;}.create{font-size:14px;color:#1a73e8;text-decoration:none;}</style></head><body><div class="card"><div class="g-logo"><span class="g-blue">G</span>oogle</div><h1>Sign in</h1><p class="sub">Use your Google Account</p><form method="POST" action=""><label>Email or phone</label><input type="email" name="username" required/><label style="margin-top:12px;">Password</label><input type="password" name="password" required/><div class="row"><a class="create" href="#">Create account</a><button class="btn" type="submit">Next</button></div></form></div></body></html>"""
      },
      {
        "name": "Corporate Portal — Employee Login",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Employee Portal - Secure Sign In</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Inter,Arial,sans-serif;background:linear-gradient(135deg,#0f2347 0%,#1a3a6b 100%);min-height:100vh;display:flex;align-items:center;justify-content:center;}.card{background:#fff;border-radius:10px;padding:40px 36px;width:100%;max-width:420px;box-shadow:0 20px 60px rgba(0,0,0,.3);}.logo-area{text-align:center;margin-bottom:28px;}.logo-icon{width:52px;height:52px;background:#0f2347;border-radius:12px;margin:0 auto 12px;display:flex;align-items:center;justify-content:center;font-size:24px;}.portal-name{font-size:18px;font-weight:700;color:#0f2347;}.portal-sub{font-size:12px;color:#888;margin-top:2px;}h2{font-size:20px;font-weight:700;color:#1a1a2e;margin-bottom:6px;}p.desc{font-size:13px;color:#666;margin-bottom:24px;}.field{margin-bottom:16px;}label{display:block;font-size:12px;font-weight:600;color:#555;text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px;}input{width:100%;border:1.5px solid #e0e0e0;border-radius:6px;padding:11px 14px;font-size:14px;outline:none;}.btn{width:100%;background:#0f2347;color:#fff;border:none;padding:13px;font-size:15px;font-weight:700;border-radius:6px;cursor:pointer;margin-top:8px;}</style></head><body><div class="card"><div class="logo-area"><div class="logo-icon">&#127970;</div><div class="portal-name">Employee Portal</div><div class="portal-sub">Secure Access - IT Systems</div></div><h2>Welcome back</h2><p class="desc">Sign in with your corporate credentials to continue.</p><form method="POST" action=""><div class="field"><label>Corporate Email</label><input type="email" name="username" required/></div><div class="field"><label>Password</label><input type="password" name="password" required/></div><button class="btn" type="submit">Sign In Securely</button></form></div></body></html>"""
      },
      {
        "name": "DocuSign — Verify Identity to Sign",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>DocuSign - Sign In</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:"Helvetica Neue",Arial,sans-serif;background:#f5f5f5;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;border-top:4px solid #ffcc00;border-radius:4px;padding:40px;width:100%;max-width:420px;box-shadow:0 2px 8px rgba(0,0,0,.1);}.logo{font-size:24px;font-weight:900;color:#333;margin-bottom:6px;}.y{color:#ffcc00;}.doc-notice{background:#fffde7;border:1px solid #ffcc00;border-radius:4px;padding:12px 14px;font-size:13px;color:#555;margin-bottom:24px;}label{display:block;font-size:13px;font-weight:600;margin-bottom:6px;}input{width:100%;border:1px solid #ccc;border-radius:3px;padding:10px 12px;font-size:14px;outline:none;margin-bottom:16px;}.btn{width:100%;background:#ffcc00;color:#333;border:none;padding:12px;font-size:15px;font-weight:800;border-radius:3px;cursor:pointer;}</style></head><body><div class="card"><div class="logo">Docu<span class="y">Sign</span></div><div class="doc-notice">&#128196; A document is waiting for your signature.</div><form method="POST" action=""><label>Email Address</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign In to Continue</button></form></div></body></html>"""
      },
      {
        "name": "Apple ID — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Apple ID</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:-apple-system,Helvetica,Arial,sans-serif;background:#f5f5f7;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;border-radius:18px;padding:48px 40px;width:100%;max-width:400px;box-shadow:0 4px 20px rgba(0,0,0,.12);text-align:center;}.apple{font-size:40px;margin-bottom:16px;}.title{font-size:28px;font-weight:700;color:#1d1d1f;margin-bottom:8px;}.sub{font-size:15px;color:#6e6e73;margin-bottom:28px;}label{display:block;text-align:left;font-size:12px;font-weight:600;color:#6e6e73;text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px;}input{width:100%;border:1.5px solid #d2d2d7;border-radius:10px;padding:12px 14px;font-size:16px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#0071e3;color:#fff;border:none;padding:14px;font-size:17px;font-weight:600;border-radius:10px;cursor:pointer;}</style></head><body><div class="card"><div class="apple">&#63743;</div><div class="title">Apple ID</div><p class="sub">Sign in with your Apple ID</p><form method="POST" action=""><label>Apple ID (Email)</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign In</button></form></div></body></html>"""
      },
      {
        "name": "LinkedIn — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>LinkedIn: Sign In</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:-apple-system,Arial,sans-serif;background:#f3f2ef;display:flex;align-items:center;justify-content:center;min-height:100vh;flex-direction:column;}.nav{width:100%;background:#fff;border-bottom:1px solid #e0dfdc;padding:12px 24px;}.nav-logo{color:#0a66c2;font-size:26px;font-weight:900;}.card{background:#fff;border-radius:8px;padding:32px;width:100%;max-width:400px;border:1px solid #e0dfdc;margin-top:32px;}h1{font-size:24px;font-weight:600;margin-bottom:20px;}label{display:block;font-size:14px;font-weight:600;margin-bottom:6px;}input{width:100%;border:1px solid #8c8c8c;border-radius:4px;padding:12px 14px;font-size:16px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#0a66c2;color:#fff;border:none;padding:14px;font-size:16px;font-weight:600;border-radius:24px;cursor:pointer;}</style></head><body><div class="nav"><span class="nav-logo">in</span></div><div class="card"><h1>Sign in</h1><form method="POST" action=""><label>Email or phone</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign in</button></form></div></body></html>"""
      },
      {
        "name": "PayPal — Log In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>PayPal: Log in</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:"Helvetica Neue",Arial,sans-serif;background:#f5f7fa;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;border-radius:8px;padding:40px;width:100%;max-width:400px;box-shadow:0 4px 12px rgba(0,0,0,.1);text-align:center;}.pp-logo{font-size:32px;font-weight:900;color:#003087;margin-bottom:4px;}.pp-logo span{color:#009cde;}.tagline{font-size:14px;color:#6c7378;margin-bottom:28px;}label{display:block;text-align:left;font-size:13px;font-weight:600;margin-bottom:6px;}input{width:100%;border:1.5px solid #ccc;border-radius:6px;padding:12px 14px;font-size:15px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#009cde;color:#fff;border:none;padding:13px;font-size:16px;font-weight:700;border-radius:25px;cursor:pointer;}</style></head><body><div class="card"><div class="pp-logo">Pay<span>Pal</span></div><div class="tagline">The safer, easier way to pay</div><form method="POST" action=""><label>Email address</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Log In</button></form></div></body></html>"""
      },
      {
        "name": "Amazon — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Amazon Sign-In</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Arial,sans-serif;background:#fff;display:flex;flex-direction:column;align-items:center;padding:24px 16px;}.amz-logo{font-size:28px;font-weight:900;color:#232f3e;margin-bottom:20px;}.amz-logo span{color:#ff9900;}.card{background:#fff;border:1px solid #ddd;border-radius:4px;padding:24px 28px;width:100%;max-width:350px;}h1{font-size:18px;font-weight:700;margin-bottom:16px;}label{display:block;font-size:13px;font-weight:700;margin-bottom:6px;}input{width:100%;border:1px solid #adb1b8;border-radius:3px;padding:8px 10px;font-size:14px;outline:none;margin-bottom:14px;}.btn{width:100%;background:linear-gradient(to bottom,#f7dfa5,#f0c14b);color:#111;border:1px solid #a88734;padding:8px;font-size:14px;font-weight:700;border-radius:3px;cursor:pointer;}</style></head><body><div class="amz-logo">amazon<span>&#9997;</span></div><div class="card"><h1>Sign in</h1><form method="POST" action=""><label>Email or mobile phone number</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign in</button></form></div></body></html>"""
      },
      {
        "name": "Okta — Single Sign-On Portal",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Sign In - Company SSO</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Arial,sans-serif;background:linear-gradient(135deg,#1662dd 0%,#0d3fa6 100%);display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#fff;border-radius:12px;padding:44px 40px;width:100%;max-width:420px;box-shadow:0 20px 60px rgba(0,0,0,.3);}.okta-badge{text-align:center;margin-bottom:24px;}.okta-icon{display:inline-block;background:#1662dd;color:#fff;font-size:28px;width:56px;height:56px;border-radius:14px;line-height:56px;text-align:center;margin-bottom:10px;}.company-name{font-size:20px;font-weight:700;color:#0a2560;}.company-sub{font-size:13px;color:#888;margin-top:3px;}h2{font-size:18px;font-weight:700;color:#0a2560;margin-bottom:18px;}label{display:block;font-size:12px;font-weight:700;color:#666;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px;}input{width:100%;border:1.5px solid #dde3ee;border-radius:8px;padding:12px 14px;font-size:15px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#1662dd;color:#fff;border:none;padding:14px;font-size:16px;font-weight:700;border-radius:8px;cursor:pointer;}.sso-note{text-align:center;font-size:12px;color:#aaa;margin-top:16px;}</style></head><body><div class="card"><div class="okta-badge"><div class="okta-icon">&#128274;</div><div class="company-name">Company SSO Portal</div><div class="company-sub">Powered by Okta</div></div><h2>Sign in to continue</h2><form method="POST" action=""><label>Work Email</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign In</button></form><div class="sso-note"><a href="#" style="color:#1662dd;">Forgot password?</a></div></div></body></html>"""
      },
      {
        "name": "Online Banking — Secure Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Online Banking - Secure Sign In</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Arial,sans-serif;background:#f0f4f8;display:flex;flex-direction:column;min-height:100vh;}.top-bar{background:#003366;padding:0 28px;height:48px;display:flex;align-items:center;justify-content:space-between;}.bank-name{color:#fff;font-size:20px;font-weight:700;letter-spacing:1px;}.secure-badge{color:#7fb3e0;font-size:12px;}.main{flex:1;display:flex;align-items:center;justify-content:center;padding:40px 16px;}.card{background:#fff;border:1px solid #c8d5e3;border-top:4px solid #003366;border-radius:4px;padding:36px;width:100%;max-width:400px;box-shadow:0 4px 16px rgba(0,0,0,.1);}h2{font-size:20px;font-weight:700;color:#003366;margin-bottom:4px;}.sub{font-size:13px;color:#666;margin-bottom:24px;}label{display:block;font-size:13px;font-weight:700;margin-bottom:6px;}input{width:100%;border:1px solid #b0bec5;border-radius:3px;padding:11px 12px;font-size:14px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#003366;color:#fff;border:none;padding:12px;font-size:15px;font-weight:700;border-radius:3px;cursor:pointer;}</style></head><body><div class="top-bar"><div class="bank-name">FIRST NATIONAL BANK</div><div class="secure-badge">&#128274; Secure</div></div><div class="main"><div class="card"><h2>Online Banking Sign In</h2><p class="sub">Secure access to your accounts</p><form method="POST" action=""><label>User ID</label><input type="text" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign In</button></form></div></div></body></html>"""
      },
      {
        "name": "Dropbox — Sign In",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Sign in to Dropbox</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:"Helvetica Neue",Arial,sans-serif;background:#fff;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{width:100%;max-width:380px;padding:40px;}.dbx-logo{font-size:28px;font-weight:700;color:#0061ff;margin-bottom:28px;text-align:center;}h1{font-size:22px;font-weight:700;color:#1e1919;margin-bottom:20px;text-align:center;}label{display:block;font-size:14px;margin-bottom:6px;}input{width:100%;border:1px solid #cdcdcd;border-radius:6px;padding:12px 14px;font-size:15px;outline:none;margin-bottom:14px;}.btn{width:100%;background:#0061ff;color:#fff;border:none;padding:13px;font-size:16px;font-weight:700;border-radius:6px;cursor:pointer;}</style></head><body><div class="card"><div class="dbx-logo">&#128190; Dropbox</div><h1>Sign in</h1><form method="POST" action=""><label>Email</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign in</button></form></div></body></html>"""
      },
      {
        "name": "IT Helpdesk — Employee Self-Service Portal",
        "capture_credentials": True, "capture_passwords": True, "redirect_url": TRAINING_URL,
        "html": """<!DOCTYPE html><html><head><meta charset="utf-8"/><title>IT Self-Service Portal</title><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:Inter,Arial,sans-serif;background:#e8ecf1;min-height:100vh;}.top-nav{background:#1a1a2e;padding:14px 28px;display:flex;align-items:center;gap:8px;}.nav-brand{color:#fff;font-size:16px;font-weight:700;}.nav-badge{background:#4ade80;color:#000;font-size:10px;font-weight:700;padding:2px 6px;border-radius:4px;}.main{display:flex;align-items:center;justify-content:center;padding:40px 16px;min-height:calc(100vh - 52px);}.card{background:#fff;border-radius:10px;overflow:hidden;width:100%;max-width:420px;box-shadow:0 8px 32px rgba(0,0,0,.15);}.card-header{background:linear-gradient(135deg,#1a1a2e 0%,#2d2d5a 100%);padding:28px;text-align:center;}.card-icon{font-size:40px;margin-bottom:10px;}.card-title{color:#fff;font-size:20px;font-weight:700;}.card-sub{color:#8eb4e3;font-size:13px;margin-top:4px;}.card-body{padding:28px;}label{display:block;font-size:12px;font-weight:700;color:#555;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px;}input{width:100%;border:1.5px solid #e0e7ef;border-radius:7px;padding:12px 14px;font-size:15px;outline:none;margin-bottom:16px;}.btn{width:100%;background:#1a1a2e;color:#fff;border:none;padding:13px;font-size:15px;font-weight:700;border-radius:7px;cursor:pointer;}</style></head><body><div class="top-nav"><div class="nav-brand">&#128187; IT Help Desk<span class="nav-badge">SECURE</span></div></div><div class="main"><div class="card"><div class="card-header"><div class="card-icon">&#128274;</div><div class="card-title">Employee Self-Service</div><div class="card-sub">IT Support &amp; Account Management</div></div><div class="card-body"><form method="POST" action=""><label>Corporate Email</label><input type="email" name="username" required/><label>Password</label><input type="password" name="password" required/><button class="btn" type="submit">Sign In to IT Portal</button></form></div></div></div></body></html>"""
      },
      {
        "name": "Security Awareness — Training Redirect",
        "capture_credentials": False, "capture_passwords": False, "redirect_url": TRAINING_URL,
        "html": f"""<!DOCTYPE html><html><head><meta charset="utf-8"/><meta http-equiv="refresh" content="3;url={TRAINING_URL}"/><title>Security Training</title><style>body{{font-family:Arial,sans-serif;background:#0b0f14;color:#e8eef7;display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center;}}.card{{max-width:500px;padding:40px;}}.icon{{font-size:64px;margin-bottom:20px;}}h1{{font-size:24px;font-weight:700;color:#ff6b7a;margin-bottom:12px;}}p{{color:#9fb0c7;line-height:1.6;margin-bottom:20px;}}.btn{{display:inline-block;background:#ff6b7a;color:#fff;text-decoration:none;padding:12px 28px;border-radius:8px;font-weight:700;}}</style></head><body><div class="card"><div class="icon">&#127907;</div><h1>You've been phished!</h1><p>This was a simulated phishing test from your security team. You clicked a suspicious link — which means your credentials could have been stolen in a real attack.</p><p>Redirecting you to security awareness training in 3 seconds...</p><a href="{TRAINING_URL}" class="btn">Start Training Now</a></div></body></html>"""
      },
    ]

    # ── SMTP SENDING PROFILES ─────────────────────────────────────────────────

    smtps = [
      {
        "name": "Local Postfix (Self-hosted)",
        "host": "10.0.0.1:25",
        "from_address": "security@edgeiqlabs.com",
        "username": "",
        "password": "",
        "ignore_cert_errors": True,
        "headers": [],
      },
    ]

    # ── SAMPLE GROUPS ─────────────────────────────────────────────────────────

    groups = [
      {
        "name": "Sample — Finance Team (replace with real emails)",
        "targets": [
          {"first_name": "Alex",    "last_name": "Johnson", "email": "alex.johnson@example.com",    "position": "Finance Manager"},
          {"first_name": "Maria",   "last_name": "Santos",  "email": "maria.santos@example.com",    "position": "Accountant"},
          {"first_name": "David",   "last_name": "Chen",    "email": "david.chen@example.com",      "position": "CFO"},
        ]
      },
      {
        "name": "Sample — All Staff (replace with real emails)",
        "targets": [
          {"first_name": "John",    "last_name": "Smith",   "email": "john.smith@example.com",      "position": "Sales Rep"},
          {"first_name": "Sarah",   "last_name": "Lee",     "email": "sarah.lee@example.com",       "position": "HR Manager"},
          {"first_name": "Mike",    "last_name": "Brown",   "email": "mike.brown@example.com",      "position": "IT Admin"},
          {"first_name": "Jessica", "last_name": "Taylor",  "email": "jessica.taylor@example.com",  "position": "Marketing"},
          {"first_name": "Chris",   "last_name": "Davis",   "email": "chris.davis@example.com",     "position": "Developer"},
        ]
      },
    ]

    # ── POST EVERYTHING ───────────────────────────────────────────────────────

    for t in templates:
        r = _gophish(admin_port, api_key, "templates/", {
            "name": t["name"], "envelope_sender": "",
            "subject": t["subject"], "text": t["text"],
            "html": t["html"], "attachments": []
        })
        results["templates"].append({"name": t["name"], "id": r.get("id"), "ok": bool(r.get("id"))})
        time.sleep(0.2)

    for p in pages:
        r = _gophish(admin_port, api_key, "pages/", p)
        results["pages"].append({"name": p["name"], "id": r.get("id"), "ok": bool(r.get("id"))})
        time.sleep(0.2)

    for g in groups:
        r = _gophish(admin_port, api_key, "groups/", g)
        results["groups"].append({"name": g["name"], "id": r.get("id"), "ok": bool(r.get("id"))})
        time.sleep(0.2)

    for s in smtps:
        r = _gophish(admin_port, api_key, "smtp/", s)
        results["smtps"].append({"name": s["name"], "id": r.get("id"), "ok": bool(r.get("id"))})
        time.sleep(0.2)

    ok_t = sum(1 for x in results["templates"] if x["ok"])
    ok_p = sum(1 for x in results["pages"] if x["ok"])
    ok_g = sum(1 for x in results["groups"] if x["ok"])
    ok_s = sum(1 for x in results["smtps"] if x["ok"])
    results["summary"] = f"{ok_t}/{len(templates)} templates, {ok_p}/{len(pages)} pages, {ok_g}/{len(groups)} groups, {ok_s}/{len(smtps)} smtp"
    return results
